export const LOAD_DESCRIPTORS_REQUEST = 'LOAD_DESCRIPTORS_REQUEST';
export const LOAD_DESCRIPTORS_SUCCESS = 'LOAD_DESCRIPTORS_SUCCESS';
export const LOAD_DESCRIPTORS_FAILURE = 'LOAD_DESCRIPTORS_FAILURE';

export const CHANGE_APP_NAME = 'CHANGE_APP_NAME';
export const ADD_CONFIG = 'ADD_CONFIG';
export const SELECT_CONFIG = 'SELECT_CONFIG';

export const CHANGE_CONFIG_NAME = 'CHANGE_CONFIG_NAME';
export const CHANGE_CONFIG_DESCRIPTOR = 'CHANGE_CONFIG_DESCRIPTOR';

export const CHECK_OWNER_REQUEST = 'CHECK_OWNER_REQUEST';
export const CHECK_OWNER_SUCCESS = 'CHECK_OWNER_SUCCESS';
export const CHECK_OWNER_FAILURE = 'CHECK_OWNER_FAILURE';
